using UnityEngine;
using UnityEngine.UI; 

public class SpatulaController : MonoBehaviour
{
    private bool isHolding = false; 
    private bool isReturningToStart = false; 
    
    // 🎥 เปลี่ยนตัวแปรหลักมาใช้ตัวที่เลือกกำหนดได้เอง ป้องกันปัญหากล้องหลายตัวตีกัน
    private Camera activeCamera;

    private Vector3 initialPosition;    
    private Quaternion initialRotation; 
    private Vector3 lastPosition; 
    private Collider spatulaCollider;

    [Header("ระบบล็อกกล้องเฉพาะตัว (ป้องกันเอ๋อเมื่อมีกล้องหลายตัว)")]
    [Tooltip("ลากกล้องตัวที่ 3 (กล้องที่ใช้คุมการทำอาหารในซีนนี้) มาหย่อนใส่ช่องนี้ได้เลย")]
    public Camera customCamera;

    [Header("Spatula Rotation Setup")]
    public Vector3 lockedRotation = new Vector3(-45f, 180f, 0f); 
    public Vector3 fpsRotation = new Vector3(0f, 180f, 0f);

    [Header("ระบบล็อกขอบเขตกระทะแบบอิสระ (Custom Boundary)")]
    public Transform customBoundary; 

    [Header("FPS Mode Position (ตอนกดหยิบตะหลิวมาถือ)")]
    public Vector3 fpsOffset = new Vector3(1f, -1f, -0.2f);

    [Header("ความเร็วระบบดูดกลับ")]
    public float returnSpeed = 8.0f;

    [Header("UI Control")]
    [Tooltip("ลาก GameObject ของปุ่ม 'วางตะหลิว' (PutDownButton) มาใส่ช่องนี้")]
    public GameObject putDownButtonObject; 
    [Tooltip("ลาก GameObject ของหลอดสไลเดอร์ (StirFrySlider) มาใส่ช่องนี้")]
    public GameObject stirFrySliderObject; 

    [Header("ระบบคะแนนการผัด (Stir Fry Progress)")]
    public StirFryManager stirFryManager; 
    public float progressMultiplier = 0.5f;

    void Start()
    {
        // 🛠️ ลอจิกเลือกกล้อง: ถ้ามีการลากกล้องตัวที่ 3 มาใส่ในช่องกิซโม ให้เลือกใช้ตัวนั้นทันที
        // แต่ถ้าลืมลากใส่ (เป็นค่าว่าง) จะยอมถอยกลับไปใช้ Camera.main ตัวหลักเพื่อความปลอดภัยครับ
        if (customCamera != null)
        {
            activeCamera = customCamera;
        }
        else
        {
            activeCamera = Camera.main;
            Debug.LogWarning($"[Spatula] ไม่พบการใส่กล้องในช่อง Custom Camera จึงสลับไปใช้ Camera.main ส่วนกลาง");
        }

        initialPosition = transform.position;
        initialRotation = transform.rotation;
        lastPosition = transform.position;
        spatulaCollider = GetComponent<Collider>();

        if (putDownButtonObject != null) putDownButtonObject.SetActive(false);
        if (stirFrySliderObject != null) stirFrySliderObject.SetActive(false);

        UpdateSpatulaInteractable();

        if (customBoundary == null)
        {
            GameObject tempBoundary = new GameObject("CustomBoundary_AutoGenerated");
            tempBoundary.transform.position = transform.position;
            customBoundary = tempBoundary.transform;
        }

        if (stirFryManager == null)
        {
            stirFryManager = FindFirstObjectByType<StirFryManager>();
        }
    }

    void Update()
    {
        UpdateSpatulaInteractable();
        HandleFPSControl();

        if (isReturningToStart)
        {
            transform.position = Vector3.Lerp(transform.position, initialPosition, Time.deltaTime * returnSpeed);
            transform.rotation = Quaternion.Lerp(transform.rotation, initialRotation, Time.deltaTime * returnSpeed);

            if (Vector3.Distance(transform.position, initialPosition) < 0.05f)
            {
                transform.position = initialPosition;
                transform.rotation = initialRotation;
                isReturningToStart = false;
            }
        }
    }

    bool CanPickupSpatula()
    {
        return PanPrepManager.Instance.IsAllPrepDone;
    }

    void UpdateSpatulaInteractable()
    {
        if (spatulaCollider == null) return;
        spatulaCollider.enabled = isHolding || CanPickupSpatula();
    }

    void HandleFPSControl()
    {
        if (isReturningToStart) return;

        if (Input.GetMouseButtonDown(0))
        {
            // 🎯 จุดที่ 1: เปลี่ยน Raycast ตอนเช็คหยิบตะหลิวให้ยิงผ่านหน้ากล้อง activeCamera (กล้องตัวที่ 3)
            Ray ray = activeCamera.ScreenPointToRay(Input.mousePosition);
            RaycastHit hit;

            if (!isHolding && CanPickupSpatula() && !PanDragCoordinator.HasActiveInteraction && Physics.Raycast(ray, out hit))
            {
                if (PanDragCoordinator.IsHitOnObject(hit, transform))
                {
                    if (PanDragCoordinator.TryBegin(this))
                    {
                        isHolding = true;
                        lastPosition = transform.position; 
                        
                        if (stirFrySliderObject != null)
                        {
                            stirFrySliderObject.SetActive(true);
                        }
                    }
                    return;
                }
            }
        }

        if (isHolding)
        {
            PanDragCoordinator.Maintain(this);
            if (Input.GetMouseButton(0))
            {
                float currentHeight = customBoundary.position.y;
                Plane projectPlane = new Plane(Vector3.up, new Vector3(0, currentHeight, 0));
                
                // 🎯 จุดที่ 2: เปลี่ยน Raycast ระบบคำนวณการลากผัดวนในกระทะให้ยิงผ่านกล้อง activeCamera 
                Ray ray = activeCamera.ScreenPointToRay(Input.mousePosition);
                float enter = 0.0f;

                if (projectPlane.Raycast(ray, out enter))
                {
                    Vector3 targetWorldPos = ray.GetPoint(enter);
                    Vector3 calculatedPos = new Vector3(targetWorldPos.x, currentHeight, targetWorldPos.z);

                    if (customBoundary != null)
                    {
                        Vector3 centerPos = new Vector3(customBoundary.position.x, currentHeight, customBoundary.position.z);
                        Vector3 offsetFromCenter = calculatedPos - centerPos;
                        
                        float radius = customBoundary.localScale.x;
                        
                        offsetFromCenter = Vector3.ClampMagnitude(offsetFromCenter, radius);
                        transform.position = centerPos + offsetFromCenter;
                    }
                    else
                    {
                        transform.position = calculatedPos;
                    }

                    transform.rotation = Quaternion.Euler(lockedRotation);

                    float moveDistance = Vector3.Distance(transform.position, lastPosition);
                    
                    if (moveDistance > 0.001f && stirFryManager != null)
                    {
                        float progressAmount = moveDistance * progressMultiplier;
                        stirFryManager.IncreaseProgress(progressAmount); 
                    }

                    lastPosition = transform.position;
                }
            }
            else
            {
                // 🎯 จุดที่ 3: เปลี่ยนระบบคำนวณค่าพิกัดลอยตามเมาส์ในโหมด FPS ให้แปลงตำแหน่งอิงจากกล้อง activeCamera
                Vector3 fpsPos = activeCamera.transform.TransformPoint(fpsOffset);
                transform.position = Vector3.Lerp(transform.position, fpsPos, Time.deltaTime * 10f);
                transform.rotation = Quaternion.Lerp(transform.rotation, Quaternion.Euler(fpsRotation), Time.deltaTime * 10f);
            }
        }
    }

    public void PutDownSpatula()
    {
        if (isHolding)
        {
            isHolding = false;
            isReturningToStart = true; 
            PanDragCoordinator.End(this);

            if (putDownButtonObject != null) putDownButtonObject.SetActive(false);
            if (stirFrySliderObject != null) stirFrySliderObject.SetActive(false);
        }
    }

    private void OnDrawGizmosSelected()
    {
        if (customBoundary != null)
        {
            Gizmos.color = Color.red;
            Gizmos.DrawWireSphere(customBoundary.position, customBoundary.localScale.x);
        }
    }
}