using UnityEngine;
using UnityEngine.Events;
using UnityEngine.UI;

public class SpatulaController : MonoBehaviour
{
    private bool isHolding = false;
    private bool isReturningToStart = false;
    private bool hasInvokedPrepDoneEvent = false;

    // 🎥 ตัวแปรกล้องที่ใช้งานอยู่
    private Camera activeCamera;

    private Vector3 initialPosition;
    private Quaternion initialRotation;
    private Vector3 lastPosition;
    private Collider spatulaCollider;
    private float stirDistanceAccumulator;

    // 🎯 ตัวแปรนับคะแนนที่ได้รับจากตะหลิวชิ้นนี้
    private int currentSpatulaScore = 0;

    [Header("Score Cap Setup")]
    [Tooltip("คะแนนสูงสุดที่ยอมให้เก็บได้จากตะหลิว")]
    public int maxScore = 50;

    [Header("ระบบล็อกกล้องเฉพาะตัว (ป้องกันเอ๋อเมื่อมีกล้องหลายตัว)")]
    [Tooltip("ลากกล้องตัวที่ใช้คุมการทำอาหารในซีนนี้มาใส่ หากปล่อยว่างจะใช้ Camera.main")]
    public Camera customCamera;

    [Header("Spatula Rotation Setup")]
    public Vector3 lockedRotation = new Vector3(-45f, 180f, 0f);
    public Vector3 fpsRotation = new Vector3(0f, 180f, 0f);

    [Header("ระบบล็อกขอบเขตกระทะแบบอิสระ (Custom Boundary)")]
    public Transform customBoundary;

    [Header("FPS Mode Position (ตอนกดหยิบตะหลิวมาถือ)")]
    public Vector3 fpsOffset = new Vector3(1f, -1f, -0.2f);

    [Header("ความเร็วระบบดูดกลับ")]
    public float returnSpeed = 8.0f;

    [Header("UI Control")]
    [Tooltip("ลาก GameObject ของปุ่ม 'วางตะหลิว' (PutDownButton) มาใส่ช่องนี้")]
    public GameObject putDownButtonObject;
    [Tooltip("ลาก GameObject ของหลอดสไลเดอร์ (StirFrySlider) มาใส่ช่องนี้")]
    public GameObject stirFrySliderObject;

    [Header("ระบบคะแนนการผัด (Stir Fry Progress)")]
    public StirFryManager stirFryManager;
    public float progressMultiplier = 0.5f;

    [Header("ระบบกระทะร้อน / เขย่ากระทะ")]
    [Tooltip("ลาก PanShakeController จาก prefab กระทะมาใส่")]
    public PanShakeController panShakeController;
    [Tooltip("เพิ่มความสุกเมื่อเขย่ากระทะสำเร็จ 1 ครั้ง")]
    public float panShakeProgressBoost = 3f;

    [Header("Events")]
    [Tooltip("เรียกเมื่อใส่วัตถุดิบครบแล้ว")]
    public UnityEvent onAllPrepDone = new UnityEvent();

    void Start()
    {
        if (customCamera != null)
        {
            activeCamera = customCamera;
        }
        else
        {
            activeCamera = Camera.main;
        }

        initialPosition = transform.position;
        initialRotation = transform.rotation;
        lastPosition = transform.position;
        spatulaCollider = GetComponent<Collider>();

        if (putDownButtonObject != null) putDownButtonObject.SetActive(false);
        if (stirFrySliderObject != null) stirFrySliderObject.SetActive(false);

        UpdateSpatulaInteractable();

        if (customBoundary == null)
        {
            GameObject tempBoundary = new GameObject("CustomBoundary_AutoGenerated");
            tempBoundary.transform.position = transform.position;
            customBoundary = tempBoundary.transform;
        }

        if (stirFryManager == null)
        {
            stirFryManager = FindFirstObjectByType<StirFryManager>();
        }
    }

    void Update()
    {
        if (customCamera == null && activeCamera != Camera.main && Camera.main != null)
        {
            activeCamera = Camera.main;
        }

        TryInvokePrepDoneEvent();
        UpdateSpatulaInteractable();
        HandleFPSControl();

        if (isReturningToStart)
        {
            transform.position = Vector3.Lerp(transform.position, initialPosition, Time.deltaTime * returnSpeed);
            transform.rotation = Quaternion.Lerp(transform.rotation, initialRotation, Time.deltaTime * returnSpeed);

            if (Vector3.Distance(transform.position, initialPosition) < 0.05f)
            {
                transform.position = initialPosition;
                transform.rotation = initialRotation;
                isReturningToStart = false;
            }
        }
    }

    bool CanPickupSpatula()
    {
        return PanPrepManager.Instance != null && PanPrepManager.Instance.IsAllPrepDone;
    }

    void TryInvokePrepDoneEvent()
    {
        if (hasInvokedPrepDoneEvent || !CanPickupSpatula()) return;

        hasInvokedPrepDoneEvent = true;
        onAllPrepDone.Invoke();
    }

    void UpdateSpatulaInteractable()
    {
        if (spatulaCollider == null) return;
        spatulaCollider.enabled = isHolding || CanPickupSpatula();
    }

    void HandleFPSControl()
    {
        if (isReturningToStart || activeCamera == null) return;

        if (Input.GetMouseButtonDown(0))
        {
            Ray ray = activeCamera.ScreenPointToRay(Input.mousePosition);
            RaycastHit hit;

            if (!isHolding && CanPickupSpatula() && !PanDragCoordinator.HasActiveInteraction && Physics.Raycast(ray, out hit))
            {
                if (PanDragCoordinator.IsHitOnObject(hit, transform))
                {
                    if (PanDragCoordinator.TryBegin(this))
                    {
                        isHolding = true;
                        lastPosition = transform.position;

                        if (stirFrySliderObject != null)
                        {
                            stirFrySliderObject.SetActive(true);
                        }
                    }
                    return;
                }
            }
        }

        if (isHolding)
        {
            HandlePanShakeInput();
            PanDragCoordinator.Maintain(this);

            if (Input.GetMouseButton(0))
            {
                float currentHeight = customBoundary.position.y;
                Plane projectPlane = new Plane(Vector3.up, new Vector3(0, currentHeight, 0));

                Ray ray = activeCamera.ScreenPointToRay(Input.mousePosition);
                float enter = 0.0f;

                if (projectPlane.Raycast(ray, out enter))
                {
                    Vector3 targetWorldPos = ray.GetPoint(enter);
                    Vector3 calculatedPos = new Vector3(targetWorldPos.x, currentHeight, targetWorldPos.z);

                    if (customBoundary != null)
                    {
                        Vector3 centerPos = new Vector3(customBoundary.position.x, currentHeight, customBoundary.position.z);
                        Vector3 offsetFromCenter = calculatedPos - centerPos;

                        float radius = customBoundary.localScale.x;

                        offsetFromCenter = Vector3.ClampMagnitude(offsetFromCenter, radius);
                        transform.position = centerPos + offsetFromCenter;
                    }
                    else
                    {
                        transform.position = calculatedPos;
                    }

                    transform.rotation = Quaternion.Euler(lockedRotation);

                    float moveDistance = Vector3.Distance(transform.position, lastPosition);

                    if (moveDistance > 0.001f && stirFryManager != null)
                    {
                        float progressAmount = moveDistance * progressMultiplier;
                        stirFryManager.IncreaseProgress(progressAmount);

                        stirDistanceAccumulator += moveDistance;
                        if (stirDistanceAccumulator >= 5f)
                        {
                            int stirPoints = Mathf.FloorToInt(stirDistanceAccumulator / 5f) * 2;
                            stirDistanceAccumulator %= 5f;

                            // 🎯 เพิ่มคะแนนการผัด (จำกัดไม่เกิน 50)
                            AddCappedScore(stirPoints);
                        }
                    }

                    lastPosition = transform.position;
                }
            }
            else
            {
                Vector3 fpsPos = activeCamera.transform.TransformPoint(fpsOffset);
                transform.position = Vector3.Lerp(transform.position, fpsPos, Time.deltaTime * 10f);
                transform.rotation = Quaternion.Lerp(transform.rotation, Quaternion.Euler(fpsRotation), Time.deltaTime * 10f);
            }
        }
    }

    void HandlePanShakeInput()
    {
        if (panShakeController == null) return;

#if UNITY_EDITOR || UNITY_STANDALONE
        if (Input.GetKeyDown(KeyCode.W) && panShakeController.TriggerShake())
            OnPanShakeTriggered();
#endif

        if (Input.acceleration.sqrMagnitude >= panShakeController.ShakeThreshold
            && panShakeController.TriggerShake())
        {
            OnPanShakeTriggered();
        }
    }

    void OnPanShakeTriggered()
    {
        // 🎯 เพิ่มคะแนนเขย่ากระทะ (จำกัดไม่เกิน 50)
        AddCappedScore(15);

        if (stirFryManager != null && panShakeProgressBoost > 0f)
            stirFryManager.IncreaseProgress(panShakeProgressBoost);
    }

    // 💡 ฟังก์ชันคำนวณและเพิ่มคะแนนโดยใช้ Local Tracker (ปลอดภัย ไม่ติด Error แน่นอน)
    private void AddCappedScore(int pointsToAdd)
    {
        if (currentSpatulaScore >= maxScore) return;

        int allowedPoints = Mathf.Min(pointsToAdd, maxScore - currentSpatulaScore);

        if (allowedPoints > 0)
        {
            currentSpatulaScore += allowedPoints;

            if (ScoreManager.Instance != null)
            {
                ScoreManager.Instance.AddScore(allowedPoints);
            }
            else if (GameplayScore.Instance != null)
            {
                GameplayScore.Instance.AddScore(allowedPoints);
            }
        }
    }

    public void PutDownSpatula()
    {
        if (isHolding)
        {
            isHolding = false;
            PanDragCoordinator.End(this);

            if (putDownButtonObject != null) putDownButtonObject.SetActive(false);
            if (stirFrySliderObject != null) stirFrySliderObject.SetActive(false);

            Destroy(gameObject);
        }
    }

    private void OnDrawGizmosSelected()
    {
        if (customBoundary != null)
        {
            Gizmos.color = Color.red;
            Gizmos.DrawWireSphere(customBoundary.position, customBoundary.localScale.x);
        }
    }
}