using UnityEngine;
using UnityEngine.Events;
using UnityEngine.UI;

public class SpatulaController : MonoBehaviour
{
    private bool isHolding = false;
    private bool isReturningToStart = false;
    private bool hasInvokedPrepDoneEvent = false;

    // 🍳 true เฉพาะเฟรมที่กำลังลากตะหลิวผัดจริงๆ ให้ CookingSystem3D เอาไปเช็คก่อนเพิ่ม % การทำอาหาร
    public static bool IsStirringNow { get; private set; }

    // 🎥 ตัวแปรกล้องที่ใช้งานอยู่
    private Camera activeCamera;

    private Vector3 initialPosition;
    private Quaternion initialRotation;
    private Vector3 lastPosition;
    private Collider spatulaCollider;
    private float stirDistanceAccumulator;

    // 🎯 ตัวแปรนับคะแนนเฉพาะตะหลิวอันนี้ (เริ่มที่ 0 ใหม่เสมอเมื่อเริ่มสเตชัน)
    private int currentSpatulaScore = 0;

    [Header("Score Cap Setup")]
    [Tooltip("คะแนนสูงสุดที่ยอมให้เก็บได้จากตะหลิวชิ้นนี้")]
    public int maxScore = 50;

    [Header("ระบบล็อกกล้องเฉพาะตัว (ป้องกันเอ๋อเมื่อมีกล้องหลายตัว)")]
    [Tooltip("ลากกล้องตัวที่ใช้คุมการทำอาหารในซีนนี้มาใส่ หากปล่อยว่างจะใช้ Camera.main")]
    public Camera customCamera;

    [Header("Spatula Rotation Setup")]
    public Vector3 lockedRotation = new Vector3(-45f, 180f, 0f);
    public Vector3 fpsRotation = new Vector3(0f, 180f, 0f);

    [Header("ระบบล็อกขอบเขตกระทะแบบอิสระ (Custom Boundary)")]
    public Transform customBoundary;

    [Header("FPS Mode Position (ตอนกดหยิบตะหลิวมาถือ)")]
    public Vector3 fpsOffset = new Vector3(1f, -1f, -0.2f);

    [Header("ความเร็วระบบดูดกลับ")]
    public float returnSpeed = 8.0f;

    [Header("UI Control")]
    [Tooltip("ลาก GameObject ของปุ่ม 'วางตะหลิว' (PutDownButton) มาใส่ช่องนี้")]
    public GameObject putDownButtonObject;
    [Tooltip("ลาก GameObject ของหลอดสไลเดอร์ (StirFrySlider) มาใส่ช่องนี้")]
    public GameObject stirFrySliderObject;

    [Header("ระบบคะแนนการผัด (Stir Fry Progress)")]
    public StirFryManager stirFryManager;
    public float progressMultiplier = 0.5f;

    [Header("ผูกกับระบบควบคุมไฟ (ถ้ามี) — ห้ามให้ปุ่มวางตะหลิวโผล่ก่อนไฟสุกจริง")]
    [Tooltip("ถ้าใส่ไว้ ปุ่มวางตะหลิว/onSpatulaScoreFull จะรอจนกว่า CookingSystem3D.isCooked เป็น true ก่อน แม้คะแนนจะครบ maxScore แล้วก็ตาม")]
    public CookingSystem3D linkedCookingSystem;

    [Header("ระบบกระทะร้อน / เขย่ากระทะ")]
    [Tooltip("ลาก PanShakeController จาก prefab กระทะมาใส่")]
    public PanShakeController panShakeController;
    [Tooltip("เพิ่มความสุกเมื่อเขย่ากระทะสำเร็จ 1 ครั้ง")]
    public float panShakeProgressBoost = 3f;

    [Header("Events")]
    [Tooltip("เรียกเมื่อใส่วัตถุดิบครบแล้ว")]
    public UnityEvent onAllPrepDone = new UnityEvent();
    [Tooltip("เรียกเมื่อเก็บคะแนนตะหลิวครบ maxScore แล้ว")]
    public UnityEvent onSpatulaScoreFull = new UnityEvent();
    [Tooltip("เรียกเมื่อกดวางตะหลิวสำเร็จ (นำไปเปิดขั้นตอนถัดไปในสเตชัน)")]
    public UnityEvent onSpatulaPutDown = new UnityEvent();

    void Start()
    {
        // 💡 1. ล้างสถานะการผัดค้างจากรอบเก่าทันที
        PanDragCoordinator.End(this);
        currentSpatulaScore = 0;
        stirDistanceAccumulator = 0f;
        isHolding = false;
        isReturningToStart = false;

        initialPosition = transform.position;
        initialRotation = transform.rotation;
        lastPosition = transform.position;
        spatulaCollider = GetComponent<Collider>();

        // 💡 2. ค้นหา Reference สำหรับสเตชันรอบปัจจุบัน
        FindAndSetupReferences();

        // ซ่อน UI ไว้ก่อนเมื่อเริ่มต้นสเตชัน
        if (putDownButtonObject != null) putDownButtonObject.SetActive(false);
        if (stirFrySliderObject != null) stirFrySliderObject.SetActive(false);

        UpdateSpatulaInteractable();

        if (customBoundary == null)
        {
            GameObject tempBoundary = new GameObject("CustomBoundary_AutoGenerated");
            tempBoundary.transform.position = transform.position;
            customBoundary = tempBoundary.transform;
        }
    }

    private void FindAndSetupReferences()
    {
        if (customCamera != null)
        {
            activeCamera = customCamera;
        }
        else
        {
            activeCamera = GetComponentInParent<Camera>();
            if (activeCamera == null) activeCamera = Camera.main;
        }

        if (stirFryManager == null)
        {
            stirFryManager = GetComponentInParent<StirFryManager>();
            if (stirFryManager == null) stirFryManager = FindFirstObjectByType<StirFryManager>();
        }

        // ค้นหาปุ่มวางตะหลิวใหม่อัตโนมัติในสเตชันปัจจุบัน
        if (putDownButtonObject == null)
        {
            Transform foundButton = transform.root.Find("Canvas/PutDownButton");
            if (foundButton != null)
            {
                putDownButtonObject = foundButton.gameObject;
            }
            else
            {
                GameObject taggedBtn = GameObject.FindWithTag("PutDownButton");
                if (taggedBtn != null) putDownButtonObject = taggedBtn;
            }
        }
    }

    void Update()
    {
        // 🔒 ห้ามใช้ตะหลิวระหว่างนับเวลาถอยหลังก่อนเริ่มเกม
        if (CountdownController.IsCountdownActive)
            return;
        if (MultiplayerGameManager.Instance != null &&
            (!MultiplayerGameManager.IsSpawnedReady || !MultiplayerGameManager.Instance.GameStarted))
            return;

        if (activeCamera == null)
        {
            activeCamera = Camera.main;
        }

        TryInvokePrepDoneEvent();
        UpdateSpatulaInteractable();
        HandleFPSControl();

        // ⏳ ถ้าคะแนนครบแล้วแต่ตอนนั้นไฟยังไม่สุก ให้คอยเช็คซ้ำทุกเฟรมจนกว่าจะสุกจริง ค่อยโชว์ปุ่มวางตะหลิว
        if (isHolding && linkedCookingSystem != null && linkedCookingSystem.isCooked && putDownButtonObject != null && !putDownButtonObject.activeSelf)
            CheckIfScoreFull();

        if (isReturningToStart)
        {
            transform.position = Vector3.Lerp(transform.position, initialPosition, Time.deltaTime * returnSpeed);
            transform.rotation = Quaternion.Lerp(transform.rotation, initialRotation, Time.deltaTime * returnSpeed);

            if (Vector3.Distance(transform.position, initialPosition) < 0.05f)
            {
                transform.position = initialPosition;
                transform.rotation = initialRotation;
                isReturningToStart = false;
            }
        }
    }

    bool CanPickupSpatula()
    {
        return PanPrepManager.Instance != null && PanPrepManager.Instance.IsAllPrepDone;
    }

    void TryInvokePrepDoneEvent()
    {
        if (hasInvokedPrepDoneEvent || !CanPickupSpatula()) return;

        hasInvokedPrepDoneEvent = true;
        onAllPrepDone.Invoke();
    }

    void UpdateSpatulaInteractable()
    {
        if (spatulaCollider == null) return;
        spatulaCollider.enabled = (isHolding || CanPickupSpatula()) && !isReturningToStart;
    }

    void HandleFPSControl()
    {
        IsStirringNow = false;

        if (isReturningToStart || activeCamera == null) return;

        if (Input.GetMouseButtonDown(0))
        {
            Ray ray = activeCamera.ScreenPointToRay(Input.mousePosition);
            RaycastHit hit;

            if (!isHolding && CanPickupSpatula() && !PanDragCoordinator.HasActiveInteraction && Physics.Raycast(ray, out hit))
            {
                if (PanDragCoordinator.IsHitOnObject(hit, transform))
                {
                    if (PanDragCoordinator.TryBegin(this))
                    {
                        isHolding = true;
                        lastPosition = transform.position;

                        if (stirFrySliderObject != null)
                        {
                            stirFrySliderObject.SetActive(true);
                        }

                        CheckIfScoreFull();
                    }
                    return;
                }
            }
        }

        if (isHolding)
        {
            HandlePanShakeInput();
            PanDragCoordinator.Maintain(this);

            if (Input.GetMouseButton(0))
            {
                float currentHeight = customBoundary.position.y;
                Plane projectPlane = new Plane(Vector3.up, new Vector3(0, currentHeight, 0));

                Ray ray = activeCamera.ScreenPointToRay(Input.mousePosition);
                float enter = 0.0f;

                if (projectPlane.Raycast(ray, out enter))
                {
                    Vector3 targetWorldPos = ray.GetPoint(enter);
                    Vector3 calculatedPos = new Vector3(targetWorldPos.x, currentHeight, targetWorldPos.z);

                    if (customBoundary != null)
                    {
                        Vector3 centerPos = new Vector3(customBoundary.position.x, currentHeight, customBoundary.position.z);
                        Vector3 offsetFromCenter = calculatedPos - centerPos;

                        float radius = customBoundary.localScale.x;

                        offsetFromCenter = Vector3.ClampMagnitude(offsetFromCenter, radius);
                        transform.position = centerPos + offsetFromCenter;
                    }
                    else
                    {
                        transform.position = calculatedPos;
                    }

                    transform.rotation = Quaternion.Euler(lockedRotation);

                    float moveDistance = Vector3.Distance(transform.position, lastPosition);

                    if (moveDistance > 0.001f)
                    {
                        IsStirringNow = true;

                        if (stirFryManager != null)
                        {
                            float progressAmount = moveDistance * progressMultiplier;
                            stirFryManager.IncreaseProgress(progressAmount);
                        }

                        // 🎯 สะสมระยะทางผัดเพื่อคิดคะแนน
                        stirDistanceAccumulator += moveDistance;
                        if (stirDistanceAccumulator >= 5f)
                        {
                            int stirPoints = Mathf.FloorToInt(stirDistanceAccumulator / 5f) * 2;
                            stirDistanceAccumulator %= 5f;

                            AddCappedScore(stirPoints);
                        }
                    }

                    lastPosition = transform.position;
                }
            }
            else
            {
                Vector3 fpsPos = activeCamera.transform.TransformPoint(fpsOffset);
                transform.position = Vector3.Lerp(transform.position, fpsPos, Time.deltaTime * 10f);
                transform.rotation = Quaternion.Lerp(transform.rotation, Quaternion.Euler(fpsRotation), Time.deltaTime * 10f);
            }
        }
    }

    void HandlePanShakeInput()
    {
        if (panShakeController == null) return;

#if UNITY_EDITOR || UNITY_STANDALONE
        if (Input.GetKeyDown(KeyCode.W) && panShakeController.TriggerShake())
            OnPanShakeTriggered();
#endif

        if (Input.acceleration.sqrMagnitude >= panShakeController.ShakeThreshold
            && panShakeController.TriggerShake())
        {
            OnPanShakeTriggered();
        }
    }

    void OnPanShakeTriggered()
    {
        AddCappedScore(15);

        if (stirFryManager != null && panShakeProgressBoost > 0f)
            stirFryManager.IncreaseProgress(panShakeProgressBoost);
    }

    private void AddCappedScore(int pointsToAdd)
    {
        if (currentSpatulaScore >= maxScore) return;

        int allowedPoints = Mathf.Min(pointsToAdd, maxScore - currentSpatulaScore);

        if (allowedPoints > 0)
        {
            currentSpatulaScore += allowedPoints;

            // 💡 ส่งคะแนนไปที่ ScoreManager
            ScoreManager scoreMgr = ScoreManager.Instance != null ? ScoreManager.Instance : FindFirstObjectByType<ScoreManager>();

            if (scoreMgr != null)
            {
                scoreMgr.AddScore(allowedPoints);
            }
            else if (GameplayScore.Instance != null)
            {
                GameplayScore.Instance.AddScore(allowedPoints);
            }

            CheckIfScoreFull();
        }
    }

    private void CheckIfScoreFull()
    {
        if (linkedCookingSystem != null && !linkedCookingSystem.isCooked) return;

        if (currentSpatulaScore >= maxScore)
        {
            if (putDownButtonObject == null)
            {
                FindAndSetupReferences();
            }

            if (putDownButtonObject != null)
            {
                putDownButtonObject.SetActive(true); // เปิดปุ่มวางตะหลิวเมื่อผัดครบ 50
            }

            onSpatulaScoreFull.Invoke();
        }
    }

    public void PutDownSpatula()
    {
        if (isHolding)
        {
            isHolding = false;
            PanDragCoordinator.End(this);

            if (putDownButtonObject != null) putDownButtonObject.SetActive(false);
            if (stirFrySliderObject != null) stirFrySliderObject.SetActive(false);

            isReturningToStart = true;

            if (spatulaCollider != null) spatulaCollider.enabled = false;

            onSpatulaPutDown.Invoke();
        }
    }

    private void OnDrawGizmosSelected()
    {
        if (customBoundary != null)
        {
            Gizmos.color = Color.red;
            Gizmos.DrawWireSphere(customBoundary.position, customBoundary.localScale.x);
        }
    }
}